name: CD - Deploy to Railway

on:
  workflow_run:
    workflows: ["CI za studiranje proba"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy app
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g @railway/cli

      - name: Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service studiranje-railway-proba --detach